### ISSUE TITLE
Feature request: Comments on events

### ISSUE THREAD

**Issue by eriktdesign** [austinginder/LocalMeet#1]
It would be convenient to be able to post comments on Events. After a meetup it's nice to be able to post links that were discussed, or touch base with people who were there.

**Comment by austinginder** [comment]
Yeah, that makes sense. Will work on that! Could also make sense to have a **Summary notes** section, which would just be something appended to the meeting itself to document what everyone shared.

**Comment by austinginder** [comment]
Done https://github.com/austinginder/LocalMeet/commit/66b5a4dab3553d8fbff0c916614441d39928039c and https://github.com/austinginder/LocalMeet/commit/827443eeb80db0c7cb2efa666390c19a91f3f530
